name: Assigned issue

on:
  issues:
    types:
      - assigned

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/brenohbsantos/projects/5/
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          status: In Progress
